// export const privacy = [
//     "LEGAL FRAMEWORKS FOR DATA TRANSFERS.",
//     "Effective February 10, 2022.",
//     "We maintain servers around the world and your information may be processed on servers located outside of the country where you live.",
//     "Data protection laws vary among countries, with some providing more protection than others.",
//     "Regardless of where your information is processed, we apply the same protections described in the Privacy Policy.",
//     "We also comply with certain legal frameworks relating to the transfer of data, such as the frameworks described below.",
//     "Adequacy decisions.",
//     "The European Commission has determined that certain countries outside of the European Economic Area (EEA) adequately protect personal data, which means that data can be transferred from the European Union (EU) and Norway, Liechtenstein, and Iceland to that third country without any further safeguard being necessary.",
//     "The UK and Switzerland have approved similar adequacy decisions.",
//     "We rely on the following adequacy decisions in some cases:",
//     "- European Commission adequacy decisions.",
//     "- UK adequacy regulations.",
//     "- Swiss adequacy decisions.",
//     "Standard contractual clauses.",
//     "Standard contractual clauses (SCCs) are written commitments between parties that can be used as a ground for data transfers from the EU to third countries by providing appropriate data protection safeguards.",
//     "SCCs have been approved by the European Commission and can’t be modified by the parties using them (you can see the SCCs adopted by the European Commission here, here, and here).",
//     "Such clauses have also been approved for transfers of data to countries outside the UK and Switzerland.",
//     "We rely on SCCs for our data transfers where required.",
//     "If you want to obtain a copy of the SCCs, you can contact us.",
//     "Google also incorporates SCCs into contracts with customers of its business services, including Google Workspace, Google Cloud Platform, Google Ads, and other ads and measurement products.",
//     "Learn more at privacy.google.com/businesses.",
//     "EU-U.S. and Swiss-U.S. Privacy Shield Frameworks.",
//     "As described in our Privacy Shield certification, we comply with the EU-U.S. and Swiss-U.S. Privacy Shield Frameworks as set forth by the US Department of Commerce regarding the collection, use and retention of personal information from European Union member countries (including EEA member countries) and the UK as well as Switzerland, respectively.",
//     "Google, including Google LLC and its wholly-owned US subsidiaries (unless explicitly excluded), has certified that it adheres to the Privacy Shield Principles.",
//     "Google remains responsible for any of your personal information that is shared under the Onward Transfer Principle with third parties for external processing on our behalf, as described in the 'Sharing your information' section.",
//     "To learn more about the Privacy Shield program, and to view Google’s certification, please visit the Privacy Shield website.",
//     "If you have an inquiry regarding our privacy practices in relation to our Privacy Shield certification, we encourage you to contact us.",
//     "Google is subject to the investigatory and enforcement powers of the US Federal Trade Commission (FTC).",
//     "You may also refer a complaint to your local data protection authority and we will work with them to resolve your concern.",
//     "In certain circumstances, the Privacy Shield Framework provides the right to invoke binding arbitration to resolve complaints not resolved by other means, as described in Annex I to the Privacy Shield Principles.",
//     "As of July 16, 2020, we no longer rely on the EU-U.S. Privacy Shield to transfer data that originated in the EEA or the UK to the U.S."
//   ];

  export const agreement = [
    "Effective January 5, 2022.",
    "What’s covered in these terms.",
    "We know it's tempting to skip these Terms of Service, but it’s important to establish what you can expect from us as you use Google services, and what we expect from you.",
    "These Terms of Service reflect the way Google’s business works, the laws that apply to our company, and certain things we’ve always believed to be true.",
    "As a result, these Terms of Service help define Google’s relationship with you as you interact with our services.",
    "For example, these terms include the following topic headings:",
    "What you can expect from us, which describes how we provide and develop our services.",
    "What we expect from you, which establishes certain rules for using our services.",
    "Content in Google services, which describes the intellectual property rights to the content you find in our services — whether that content belongs to you, Google, or others.",
    "In case of problems or disagreements, which describes other legal rights you have, and what to expect in case someone violates these terms.",
    "Understanding these terms is important because, by using our services, you’re agreeing to these terms.",
    "Besides these terms, we also publish a Privacy Policy.",
    "Although it’s not part of these terms, we encourage you to read it to better understand how you can update, manage, export, and delete your information.",
    "Terms.",
    "Service provider.",
    "Google services are provided by, and you’re contracting with:",
    "Google LLC.",
    "Organized under the laws of the State of Delaware, USA, and operating under the laws of the USA.",
    "1600 Amphitheatre Parkway, Mountain View, California 94043, USA.",
    "Age requirements.",
    "If you’re under the age required to manage your own Google Account, you must have your parent or legal guardian’s permission to use a Google Account.",
    "Please have your parent or legal guardian read these terms with you.",
    "If you’re a parent or legal guardian, and you allow your child to use the services, then these terms apply to you and you’re responsible for your child’s activity on the services.",
    "Some Google services have additional age requirements as described in their service-specific additional terms and policies.",
    "Your relationship with Google.",
    "These terms help define the relationship between you and Google.",
    "Broadly speaking, we give you permission to use our services if you agree to follow these terms, which reflect how Google’s business works and how we earn money.",
    "When we speak of 'Google,' 'we,' 'us,' and 'our,' we mean Google LLC and its affiliates.",
    "What you can expect from us.",
    "Provide a broad range of useful services.",
    "We provide a broad range of services that are subject to these terms, including apps and sites (like Search and Maps), platforms (like Google Shopping), integrated services (like Maps embedded in other companies’ apps or sites), and devices (like Google Nest).",
    "Many of these services also include content that you can stream or interact with.",
    "Our services are designed to work together, making it easier for you to move from one activity to the next.",
    "For example, if your Calendar event includes an address, you can click on that address and Maps can show you how to get there.",
    "Develop, improve, and update Google services.",
    "We're constantly developing new technologies and features to improve our services.",
    "For example, we use artificial intelligence and machine learning to provide you with simultaneous translations, and to better detect and block spam and malware.",
    "As part of this continual improvement, we sometimes add or remove features and functionalities, increase or decrease limits to our services, and start offering new services or stop offering old ones.",
    "When a service requires or includes downloadable software, that software sometimes updates automatically on your device once a new version or feature is available.",
    "Some services let you adjust your automatic update settings.",
    "If we make material changes that negatively impact your use of our services or if we stop offering a service, we’ll provide you with reasonable advance notice, except in urgent situations such as preventing abuse, responding to legal requirements, or addressing security and operability issues.",
    "We’ll also provide you with an opportunity to export your content from your Google Account using Google Takeout, subject to applicable law and policies.",
    "What we expect from you.",
    "Follow these terms and service-specific additional terms.",
    "The permission we give you to use our services continues as long as you comply with these terms and service-specific additional terms, which could, for example, include things like additional age requirements.",
    "We also make various policies, help centers, and other resources available to you to answer common questions and to set expectations about using our services.",
    "These resources include our Privacy Policy, Copyright Help Center, Safety Center, and other pages accessible from our policies site.",
    "Although we give you permission to use our services, we retain any intellectual property rights we have in the services.",
    "Your content.",
    "Some of our services give you the opportunity to make your content publicly available — for example, you might post a product or restaurant review that you wrote, or you might upload a blog post that you created.",
    "See the Permission to use your content section for more about your rights in your content, and how your content is used in our services.",
    "See the Removing your content section to learn why and how we might remove user-generated content from our services.",
    "If you think someone is infringing your intellectual property rights, you can send us notice of the infringement and we’ll take appropriate action.",
    "For example, we suspend or close the Google Accounts of repeat copyright infringers as described in our Copyright Help Center.",
    "Google content.",
    "Some of our services include content that belongs to Google — for example, many of the visual illustrations you see in Google Maps.",
    "You may use Google’s content as allowed by these terms and any service-specific additional terms, but we retain any intellectual property rights that we have in our content.",
    "Don’t remove, obscure, or alter any of our branding, logos, or legal notices.",
    "If you want to use our branding or logos, please see the Google Brand Permissions page.",
    "Other content.",
    "Finally, some of our services give you access to content that belongs to other people or organizations — for example, a store owner’s description of their own business, or a newspaper article displayed in Google News.",
    "You may not use this content without that person or organization’s permission, or as otherwise allowed by law.",
    "The views expressed in other people or organizations’ content are theirs, and don’t necessarily reflect Google’s views.",
    "In case of problems or disagreements.",
    "Both the law and these terms give you the right to (1) a certain quality of service, and (2) ways to fix problems if things go wrong.",
    "Warranty.",
    "We provide our services using reasonable skill and care.",
    "If we don’t meet the quality level described in this warranty, you agree to tell us and we’ll work with you to try to resolve the issue.",
    "Disclaimers.",
    "The only commitments we make about our services (including the content in the services, the specific functions of our services, or their reliability, availability, or ability to meet your needs) are provided in (1) the Warranty section; (2) the service-specific additional terms; and (3) laws that can’t be limited by these terms.",
    "Taking action in case of problems.",
    "Before taking action as described below, we’ll provide you with advance notice when reasonably possible, describe the reason for our action, and give you an opportunity to fix the problem, unless we reasonably believe that doing so would cause harm or liability to a user, third party, or Google, violate the law or a legal enforcement authority’s order, compromise an investigation, or compromise the operation, integrity, or security of our services.",
    "About these terms.",
    "By law, you have certain rights that can’t be limited by a contract like these terms of service.",
    "These terms are in no way intended to restrict those rights.",
    "These terms describe the relationship between you and Google.",
    "They don’t create any legal rights for other people or organizations, even if others benefit from that relationship under these terms.",
    "We want to make these terms easy to understand, so we’ve used examples from our services.",
    "But not all services mentioned may be available in your country.",
    "If these terms conflict with the service-specific additional terms, the additional terms will govern for that service.",
    "If it turns out that a particular term is not valid or enforceable, this will not affect any other terms.",
    "If you don’t follow these terms or the service-specific additional terms, and we don’t take action right away, that doesn’t mean we’re giving up any rights that we may have, such as taking action in the future.",
    "We may update these terms and service-specific additional terms (1) to reflect changes in our services or how we do business — for example, when we add new services, features, technologies, pricing, or benefits (or remove old ones), (2) for legal, regulatory, or security reasons, or (3) to prevent abuse or harm.",
    "If we materially change these terms or service-specific additional terms, we’ll provide you with reasonable advance notice and the opportunity to review the changes, except (1) when we launch a new service or feature, or (2) in urgent situations, such as preventing ongoing abuse or responding to legal requirements.",
    "If you don’t agree to the new terms, you should remove your content and stop using the services.",
    "You can also end your relationship with us at any time by closing your Google Account."
  ];